### ISSUE TITLE
support for failover

### ISSUE THREAD

**Issue by m-jayson** [pgigeruzh/pgpool#1]
hi. does this support failover?

**Comment by pgigeruzh** [comment]
No, it doesn't support automatic failovers (we have used it as a load balancer in a student project). You would have to change the settings in the entrypoint.sh file if you want to make it work. However, there is a significant performance impact for using pgpool and Raspberry Pis can't take advantage of it (the more clients, the better the performance but a Raspberry Pi can handle only so much).

**Comment by m-jayson** [comment]
Oh i see.. I have actually modified the scripts but the problem is the ssh part.. But in terms of performance.. I got you. hope there is a change on this new rpi 8GB
